### ISSUE TITLE
Attempt to index a boolean value on Windows

### ISSUE THREAD

**Issue by rborek** [Ajatt-Tools/mpvacious#13]
https://github.com/Ajatt-Tools/mpvacious/blob/657234cdbc39a7f15603c6f09ae3d80351a137c5/subs2srs.lua#L528
On Windows 10, using mpv 0.32.0 portable, I was hitting a Lua error here during create_deck, and after I commented that out, when trying to make a card using Ctrl + e.

I was able to fix it by changing the line to:
local file = io.open(curl_tmpfile_path, "w")
file:write(request_json)
file:close()

Posting this as an issue in case others encounter the same thing; I'm not sure if I'm somehow using the wrong Lua version or something like that. Everything else seems to work fine for me after making that change.

**Comment by tatsumoto-ren** [comment]
Thank you for the report. A Gentoo user with `Lua 5.1` previously encountered this error, but in a different part of the add-on. If you upgrade to a build by [shinchiro](https://sourceforge.net/projects/mpv-player-windows/files) it should disappear. But I'll commit the changes you propose so that other users of mpv portable don't run into it.
