### ISSUE TITLE
Is audio normalized?

### ISSUE THREAD

**Issue by Lucridius** [Ajatt-Tools/mpvacious#14]
Just a quick question, are the audio snippets that are created sound normalized?

(so if I create cards for a quiet show and a loud show, will the volume be roughly the same)

**Comment by tatsumoto-ren** [comment]
No, they aren't normalized since normalization requires passing multiple files at once. You can use [mp3gain](https://aur.archlinux.org/packages/mp3gain/) to do it yourself afterwards, or set `tie_volumes=yes` in the config file, this way you'll be able to make output volume the same as volume set in mpv.
