### ISSUE TITLE
Add furigana on the subtitles

### ISSUE THREAD

**Issue by OltiP2** [Ajatt-Tools/mpvacious#65]
Adding furigana to subs,being able to toggle it off/on

**Comment by cyphar** [comment]
Also no tool can generate correct furigana all the time (not even mecab). Things like 〜中 (じゅう・ちゅう) arguably make it impossible to generate correct furigana all the time because for some words the right reading depends on what the speaker is trying to say, which a program would struggle to guess correctly all the time.

You can use yomichan to find the reading of any word in a subtitle line by using it in clipboard monitor mode and then looking up the word.

**Comment by OltiP2** [comment]
yeah but im really bad at kanji and reading when i hear a sentence and have to look it up i find out it was because i didn't hear it well cause i knew all the words but most importanlty i understood the sentence and its really hard to read cause when i did tango n5 i always clicked show answer then i guessed the meaning so almost didn't read it at all cause i thought i need to do rtk and didn't want to cause i couldn't keep it up and i was really boring and its really hard for me to start reading i don't know what to do, retake tango n5 like its supposed to do and re do all of those all over words that i already when i hear them but cannot read or start tediously reading more

**Comment by cyphar** [comment]
You'll get better with practice. Listening is one of the harder skills to train.
