### ISSUE TITLE
Strange behavior with 's' key. 

### ISSUE THREAD

**Issue by avc1657** [Ajatt-Tools/mpvacious#7]
**Environment:**
 - OS: Manjaro
 - OS version: latest version, kernel 5.8
 - mpv version: 0.32.4

**Describe the bug**
's' key is taking screenshot and saving it at $HOME instead of setting start time to current position. But if I open advanced menu first (a), 's' works fine. Also, same for 'g' key and 'n'. Is that normal?

**To Reproduce**
1. Open a video with subtitles
2. Press 's'
3. Screenshot:'/home/user/...........

**Expected behavior**
Setting start time to current positivion properly.

**Screenshots**
https://i.imgur.com/HnttFpE.png ('s' key)

**Comment by tatsumoto-ren** [comment]
Many keys in mpv are bound by default. On top of that other mpv add-ons very often occupy various keys. So we needed a way to toggle them, otherwise the user would lose the ability to take screenshots, and so on. To minimize the possibility of keybindings overriding each other this add-on and many other add-ons add them to a different `layer`. So, the bindings only work when the menu is open, yes. When the user closes the menu, the key bindings get removed, and added again when the menu is opened again.
